version : '2'
services:
    
    # My App Rule of 3
    ruleof3:
        image: docker.jala.pro/docker-training/ruleof3:daniel.jauregui.multi
        ports:
            - '5000:5000'
        networks:
            - leinad
    
    # SonarQube
    Sonarqube:
        image: sonarqube:community
        ports:
            - '9000:9000'
        networks:
            - leinad
        depends_on:
            - Postgres
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://pgdb/sonarqube
            - SONAR_JDBC_USERNAME=postgres
            - SONAR_JDBC_PASSWORD=password
        volumes: 
            - sonarqube_data:/tmp/sq/sonarqube_data
            - sonarqube_logs:/tmp/sq/sonarqube_logs
            - sonarqube_extensions:/tmp/sq/sonarqube_extensions
    
    # Postgres
    Postgres:
        image: postgres
        networks:
            leinad:
                aliases:
                    - pgdb
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    # Jenkins
    Jenkins:
        image: jenkins/jenkins:lts-jdk11
        ports:
            - '8080:8080'
        networks:
            - leinad

    # Nexus
    Nexus:
        image: sonatype/nexus3
        ports:
            - '8081:8081'
            - '8082:8082'
            - '8083:8083'
        networks:
            - leinad
        volumes: 
            - nexus-data:/nexus-data

    # Portainer
    Portainer:
        image: portainer/portainer-ce
        ports:
            - '8002:8000'
            - '9002:9000'
        networks:
            - leinad
        restart: always
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/tmp/portainer/portainer_data
    
    # Portainer Agent
    Portainer-Agent:
        image: portainer/agent
        ports:
            - '9001:9001'
        networks:
            - leinad
        restart: always
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
    portainer_data:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
    nexus-data:


networks:
    leinad:
